---
# Create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: myns
  labels:
    app: bgg

---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-config
  namespace: myns
  labels:
    app: bgg
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.myns.svc.cluster.local

---
# Secret
apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret
  namespace: myns
  labels:
    app: bgg
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=

---
# Deployment for the DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: myns
  labels:
    app: bgg
    name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgg
      name: bgg-db-po
  template:
    metadata:
      name: bgg-db-po
      labels:
        app: bgg
        name: bgg-db-po
    spec:
      containers:
        - name: bgg-db-container
          image: stackupiss/bgg-database:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
---
# CluserIP service for DB
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: myns
  labels:
    app: bgg
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    app: bgg
    name: bgg-db-po
  ports:
    - port: 3306
      targetPort: 3306

---
# Deploy App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: myns
  labels:
    app: bgg
    name: bggapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bgg
      name: bgg-app-po
  template:
    metadata:
      name: bgg-app-po
      labels:
        app: bgg
        name: bgg-app-po
    spec:
      containers:
        - name: bgg-app-container
          image: stackupiss/bgg-backend:v1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: bgg-config
            - secretRef:
                name: bgg-secret
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
---
# NodePort service for app
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: myns
  labels:
    app: bgg
    name: bggapp-svc
spec:
  type: NodePort
  selector:
    app: bgg
    name: bgg-app-po
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
