---
# Create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: myns

---
# Secret
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: myns
  labels:
    app: minio
type: Opaque
data:
  MINIO_ROOT_USER: cm9vdA==
  MINIO_ROOT_PASSWORD: cGFzc3dvcmQ=

---
# Headless service
apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  namespace: myns
  labels:
    app: minio
    name: minio-hsvc
spec:
  clusterIP: None
  selector:
    app: minio
    name: minio-po
  ports:
    - name: server
      port: 9000
      targetPort: 9000
    - name: console
      port: 9090
      targetPort: 9090

---
# ClusterIP service
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: myns
  labels:
    app: minio
    name: minio-svc
spec:
  type: ClusterIP
  selector:
    app: minio
    name: minio-po
  ports:
    - name: server
      port: 9000
      targetPort: 9000
    - name: console
      port: 9090
      targetPort: 9090

---
# Stateful set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-sts
  namespace: myns
  labels:
    app: minio
    name: minio-sts
spec:
  replicas: 3
  serviceName: minio-hsvc
  selector:
    matchLabels:
      app: minio
      name: minio-po
  volumeClaimTemplates:
    - metadata:
        name: data-vol
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      name: minio-po
      labels:
        app: minio
        name: minio-po
    spec:
      initContainers:
        - name: busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - "chown 1001:1001 /data"
          volumeMounts:
            - name: data-vol
              mountPath: /data
      containers:
        - name: minio-container
          image: bitnami/minio:2023.10.25
          imagePullPolicy: IfNotPresent
          command:
            - minio
            - server
            - --address=:9000
            - --console-address=:9090
            - http://minio-sts-{0...2}.minio-hsvc.myns.svc.cluster.local/data
          envFrom:
            - secretRef:
                name: minio-secret
          ports:
            - name: server
              containerPort: 9000
            - name: console
              containerPort: 9090
          volumeMounts:
            - name: data-vol
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            periodSeconds: 60

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ing
  namespace: myns
  labels:
    app: minio
    name: minio-ing
spec:
  ingressClassName: nginx
  rules:
    - host: data-139.59.219.11.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-svc
                port:
                  number: 9000
    - host: console-139.59.219.11.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-svc
                port:
                  number: 9090
